//You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.
// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
  
import java.util.ArrayList;
class Solution {
    public char findTheDifference(String s, String t) {
        char[]arr1=s.toCharArray();
        char[]arr2=t.toCharArray();
        Arrays.sort(arr1);
        Arrays.sort(arr2);
        for(int i=0;i<arr1.length;i++){
                if(arr1[i]!=arr2[i]){
                    return arr2[i];
                }
        }
        return arr2[arr2.length - 1];
    }
}
